package de.tudresden.bau.cib.vl.core.service;

import java.text.SimpleDateFormat;
import java.util.Map;


public interface ConfigurationService {

	
	enum PROPERTIES {
		URL_VIRTUAL_LABORATORY,
		PATH_PARSER_REPOSITORY, PATH_ONTOLOGY_REPOSITORY, PATH_OUTPUT_FOLDER, PATH_USERS, PATH_FILES,
		PATH_BASE, PATH_TEMP_DIRECTORY, SESSION_TIME_MINUTES, PATH_RESOURCES,
		NUMBER_OF_THREADS, NR_POST_PROCESSING_THREAD, WAIT_TIME_IN_MINUTES,
		PATH_RULES,
		ONTOLOGY_EEBIM_REMOTE, ONTOLOGY_IFC_REMOTE,
		SETTING_ONTOLOGY_LANGUAGE,
		FLAG_FILTER_IFC_CLASSES_FOR_ONTOLOGY,
		ISES_GRANLUND_DECISIONMAKING_URL,
		ISES_GRANLUND_DECISIONMAKING_USER,
		ISES_GRANLUND_DECISIONMAKING_PASSWORD,
		PATH_TO_NMI_CONSTRUCTIONS, PATH_TO_NMI_CONSTRUCTIONS_TRIMO,
		PATH_TO_NMI_MATERIALS,
		PATH_TO_NMI_CLIMATES,
		PATH_TO_IBK_SIMULATION_ENVIRONMENT,
		LOAD_RESOURCES_MODE,
		CLOUD_URL,
		CLOUD_TOKEN,
		CHECK_SIMULATION_INTERVALL_IN_MS,
		TEST_MODE, FLAG_ONTOLOGY_SAVE_WITHOUT_SCHEMES
		;
	}
	
	SimpleDateFormat ISO_DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss");
	
	
	String getBaseURL();
	
	String getProperty(PROPERTIES property);
	
	Map<String, Object> getAllProperties();
	
	String getProperty(String propertyName);
	
	String[] getPropertyArray(PROPERTIES property);
	
}
